### ISSUE TITLE
Q: how do i get the author of the photo on Class Search?

### ISSUE THREAD

**Issue by FrnandMG** [salvoventura/pyunsplash#10]
"Attribution is appreciated and allows contributors to gain exposure"

**Comment by salvoventura** [comment]
Hello! You can access the author information from the `Photo` objects returned by the search. I left out exposing all the properties explicitly because there's a lot, but I should have documented the existence of `body`, which usually is sufficient to extract the needed information, and is returned as a dictionary.

To your specific question, you could do something like:

```
import pyunsplash
py_un = pyunsplash.PyUnsplash(api_key='<your Unsplash API key>')
search = py_un.search(type_='photos', query='red,car')
for photo in search.entries:
    author_info = photo.body.get('user')
    username, first, last = author_info.get('username'), author_info.get('first_name'), author_info.get('last_name')
    print("{} {} {}".format(username, first, last))
```

Please note that `author_info` contains much more information, which is coming back straight from the API.

**Comment by FrnandMG** [comment]
Great. many thanks.

**Comment by salvoventura** [comment]
Maybe I could add a feature for providing a standard attribution string, or payload that could be used rightaway. Something like the default "Photo by Jon Doe on Unsplash", with "Jon Doe" a link to his profile (if html).

What output format will you use? Text? HTML?

**Comment by FrnandMG** [comment]
That would be very useful. In particular I would use the text format.

**Comment by salvoventura** [comment]
I added the method `get_attribution()` to the `Photo` class, and made a new release.
